content: |-
  # Terraform Module: Wayfinder on Azure

  The "terraform-azurerm-wayfinder" Terraform Module can be used to provision and manage a licensed edition of [Appvia Wayfinder](https://www.appvia.io/product/) on Azure.

  ## Requirements

  To run this module, you will need the following:
  1. Product Licence Key & Instance ID: Contact sales@appvia.io for more information.
  2. (Optional) IDP App configuration details: Wayfinder integrates with an IDP for managing user access. You will need a valid Client ID, Client Secret and Server URL (or Azure Tenant ID) for setup. This does not need to be defined initially within Terraform, and can also be setup within the product. Wayfinder can provision a `localadmin` user for initial access if no IDP details are provided.
  3. A public Azure DNS Zone: This module will create DNS records for the Wayfinder API and UI endpoints, and performs a DNS01 challenge via the LetsEncrypt Issuer for valid domain certificates.
  4. Existing Virtual Network and Subnet: This module will deploy an AKS Cluster and so requires an existing vnet with outbound internet connectivity.

  ## Deployment

  Please see the [examples](./examples) directory to see how to deploy this module. To get up and running quickly with minimal pre-requisites, use the [quickstart](./examples/quickstart) example.

  ### (Optional) Connecting to an Identity Provider

  Wayfinder integrates with an IDP for managing user access. You will need a valid Client ID, Client Secret and Server URL (or Azure Tenant ID).

  This configuration is optional within Terraform, and can also be setup within the product. Please view the documentation for more information: https://docs.appvia.io/wayfinder/admin/auth

  The Authorized Redirect URI for the IDP Application should be set to: `https://${wayfinder_domain_name_api}/oauth/callback`

  **Note:** If you are using Azure Active Directory, you must:
  1. Set `azureTenantId` to your Azure Tenant ID (`serverUrl` is not required)
  2. Set the IDP type to `aad`

  #### Example: Generic IDP Configuration

  ```hcl
  wayfinder_idp_details = {
    {{ "  " }}type         = "generic"
    {{ "  " }}clientId     = "IDP-APP-CLIENT-ID"
    {{ "  " }}clientSecret = "IDP-APP-CLIENT-SECRET"
    {{ "  " }}serverUrl    = "https://example.okta.com" # Or "https://example.auth0.com/"
  }
  ```

  #### Example: Azure AD IDP Configuration

  ```hcl
  wayfinder_idp_details = {
    {{ "  " }}type          = "aad"
    {{ "  " }}clientId      = "IDP-APP-CLIENT-ID"
    {{ "  " }}clientSecret  = "IDP-APP-CLIENT-SECRET"
    {{ "  " }}azureTenantId = "12345678-1234-1234-1234-123456789012"
  }
  ```

  ## Updating Docs

  The `terraform-docs` utility is used to generate this README. Follow the below steps to update:
  1. Make changes to the `.terraform-docs.yml` file
  2. Fetch the `terraform-docs` binary (https://terraform-docs.io/user-guide/installation/)
  3. Run `terraform-docs markdown table --output-file ${PWD}/README.md --output-mode inject .`

  {{ .Inputs }}

  {{ .Outputs }}
