name: Terraform Module Validation
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - vnext

jobs:
  terraform:
      uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
      name: Terraform Module Validation
